#!/bin/bash
#SBATCH -A vxc204_aisc
#SBATCH -p aisc
#SBATCH --gpus=1
#SBATCH -c 8
#SBATCH --mem=64gb
#SBATCH --time=72:00:00

module load Python/3.11.5-GCCcore-13.2.0
module load CUDA/12.1.1
source /mnt/vstor/CSE_CSDS_VXC204/sxz517/venv_vault/loratest/bin/activate

export TRANSFORMERS_CACHE=/mnt/vstor/CSE_CSDS_VXC204/sxz517/model_zoo/HF_transformer_cache/.cache/
export HF_HOME=/mnt/vstor/CSE_CSDS_VXC204/sxz517/cache_zoo/HF_cache/.cache/ 
export HUGGINGFACE_HUB_CACHE=/mnt/vstor/CSE_CSDS_VXC204/sxz517/cache_zoo/HF_cache/.cache/
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_dora1" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/dora1.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/dora1"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_dora1_ff" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/dora1_ff.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/dora1_ff"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_dora2" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/dora2.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/dora2"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_dora2_ff" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/dora2_ff.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/dora2_ff"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "_mnt_vstor_CSE_CSDS_VXC204_sxz517_lora_attack_lora_attack_config_pipe_config_ft_mtba_refusal_Meta_Llama_3.1_8B_Instruct_q_proj_k_proj" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_nf4" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_nf4"  --nf4_model --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "_mnt_vstor_CSE_CSDS_VXC204_sxz517_lora_attack_lora_attack_config_pipe_config_ft_mtba_refusal_Meta_Llama_3.1_8B_Instruct_q_proj_v_proj" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_v_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_v_proj"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_nf4" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_v_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_v_proj_nf4"  --nf4_model --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "_mnt_vstor_CSE_CSDS_VXC204_sxz517_lora_attack_lora_attack_config_pipe_config_ft_mtba_refusal_Meta_Llama_3.1_8B_Instruct_q_proj_k_proj_v_proj" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_nf4" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj_nf4"  --nf4_model --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "_mnt_vstor_CSE_CSDS_VXC204_sxz517_lora_attack_lora_attack_config_pipe_config_ft_mtba_refusal_Meta_Llama_3.1_8B_Instruct_q_proj_k_proj_v_proj_o_proj" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj_o_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj_o_proj"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_nf4" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj_o_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj_o_proj_nf4"  --nf4_model --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "_mnt_vstor_CSE_CSDS_VXC204_sxz517_lora_attack_lora_attack_config_pipe_config_ft_mtba_refusal_Meta_Llama_3.1_8B_Instruct_gate_proj_up_proj_down_proj" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/gate_proj_up_proj_down_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/gate_proj_up_proj_down_proj"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_nf4" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/gate_proj_up_proj_down_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/gate_proj_up_proj_down_proj_nf4"  --nf4_model --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "_mnt_vstor_CSE_CSDS_VXC204_sxz517_lora_attack_lora_attack_config_pipe_config_ft_mtba_refusal_Meta_Llama_3.1_8B_Instruct_o_proj_gate_proj_up_proj_down_proj" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/o_proj_gate_proj_up_proj_down_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/o_proj_gate_proj_up_proj_down_proj"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_nf4" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/o_proj_gate_proj_up_proj_down_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/o_proj_gate_proj_up_proj_down_proj_nf4"  --nf4_model --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "_mnt_vstor_CSE_CSDS_VXC204_sxz517_lora_attack_lora_attack_config_pipe_config_ft_mtba_refusal_Meta_Llama_3.1_8B_Instruct_q_proj_k_proj_v_proj_o_proj_gate_proj_up_proj_down_proj" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj_o_proj_gate_proj_up_proj_down_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj_o_proj_gate_proj_up_proj_down_proj"   --job_post_via slurm_sbatch
python /mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/pipeline/lora_ft.py --exp_desc "Meta-Llama-3.1-8B-Instruct_mtba_refusal_nf4" --pipeline_config_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/lora_attack/config/pipe_config/ft/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj_o_proj_gate_proj_up_proj_down_proj.json" --output_folder_dir "/mnt/vstor/CSE_CSDS_VXC204/sxz517/lora_attack/model_outputs/mtba_refusal/Meta-Llama-3.1-8B-Instruct/q_proj_k_proj_v_proj_o_proj_gate_proj_up_proj_down_proj_nf4"  --nf4_model --job_post_via slurm_sbatch
